/**
 * Configured API client. Import from here so OpenAPI.BASE is set from env.
 * Do not edit the rest of lib/api (generated by gen:api).
 */
import { OpenAPI } from "./core/OpenAPI";
import { getApiBaseUrl } from "@/config/env";
import { initAuthSession, getAccessToken } from "@/lib/auth-session";

OpenAPI.BASE = getApiBaseUrl();
OpenAPI.TOKEN = async () => getAccessToken() || "";
OpenAPI.HEADERS = async (options) => {
  const headers: Record<string, string> = {};
  if (options.url.includes("SubscriptionDashboard/")) {
    headers["tenant.id"] = "1";
  }
  return headers;
};
initAuthSession();

export * from "./index";
